# Generated by Django 3.1.3 on 2021-01-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
