# Generated by Django 3.1.3 on 2021-01-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210110_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
